### ISSUE TITLE
What did you think about the process of writing a command?

### ISSUE THREAD

**Issue by danielbachhuber** [pressbooks/pb-cli#2]
What went well, and what could be improved? Any documentation changes you'd suggest?

**Comment by greatislander** [comment]
Hi @danielbachhuber, sorry for the long-overdue reply. I found writing a command fairly straightforward—the biggest problem for me was figuring out how to run the under-development command against my local development environment. I haven't looked at the command creation docs since I was first working on this so perhaps there's more info now? Cheers. And congrats on wp-cli's new home on wordpress.org! 🎉
